CREATE TABLE IF NOT EXISTS workflow_teams (
  code TEXT PRIMARY KEY,
  label TEXT NOT NULL UNIQUE,
  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)),
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
INSERT OR IGNORE INTO workflow_teams(code,label,active,created_at,updated_at) VALUES
  ('ADMIN','Administração',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('ZELADORIA','Zeladoria',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('MANUTENCAO','Manutenção',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('LIMPEZA','Limpeza',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('SERVICOS_GERAIS','Serviços gerais',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
  ('LEITURISTA','Leiturista',1,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
